version: '3.8'

services:
  #Baza Danych MySQL
  mysqldb:
    image: mysql:8.0
    container_name: terappka-mysql
    restart: always
    environment:
      MYSQL_DATABASE: terappka_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: adminroot
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  #Backend
  app:
    build: .
    container_name: terappka-backend
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/terappka_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  db_data: